### ISSUE TITLE
WSL2

### ISSUE THREAD

**Issue by AntonOfTheWoods** [tautomer/WSL_Terminator#1]
Does this definitely work on WSL2? It launches vcxsrv fine but it seems to not run the gui app properly. Shouldn't it be run using wsl.exe, not bash? I have been trying to get it to work but no combination seems to either work or show me the output so I can debug :-(

**Comment by tautomer** [comment]
Sorry for late reply. I'm not sure if I understand your problem correctly. `vcxsrv` is correcly launched, but you can't run x11 apps?

Though `bash.exe` is deprecated, it should still work right now.

One thing in my mind is that for x11 to work, `$DISPLAY` is configured differently for WSL2. [See here.](https://github.com/tautomer/WSL_Windows_Terminal#for-wsl-2) If you just launch `wsl.exe` or `bash.exe` together with `vcxsrv.exe`, does any other x11 apps run? If it doesn't, that means you need set your `$DISPLAY` properly.

It should be

```
DISPLAY=$(cat /etc/resolv.conf | grep name | cut -d' ' -f2):0
```

WSL1 doesn't have this issue.

I will also test it out some time this weekend and get back to you. (if you still have the problem)😉

**Comment by AntonOfTheWoods** [comment]
It did take me a bit to get the x11 working due to the firewall but it definitely works if I open a cmd, launch/log in via wsl then launch my app (`gnome-terminal`). 

I definitely haven't been able to get anything to launch without manually opening a cmd (or Windows Terminal) and manually launching. If you have any pointers I'd love a single click launch solution! I had Windows Terminal crash a few times and there are a few other glitches that have me still yearning for good old `gnome-terminal` (or `konsole` if required).

In unrelated news, there was a default user on my new machine (Dell) and I started using the it before creating one with a proper username. In the account I created the `gnome-terminal` app lasts 20-30 minutes before disappearing (crashing?), in the `Dell` account it behaves normally (lasts forever)...

**Comment by tautomer** [comment]
Hi Anton, I think the problem is the '-l' argument. Sometimes or on some machine, it doesn't work if `bash` is invoked by login.

If you change the `args` line in the vbs script to the following (basically just remove '-l' part and add a space after '-c')

```
args = "-c " & """DISPLAY=$(cat /etc/resolv.conf | grep name | cut -d' ' -f2):0.0 gnome-terminal"""
```

It should work.

**Comment by AntonOfTheWoods** [comment]
Thanks for the help. The line you suggest is the line I had (except I have `:0` rather than `:0.0` - both appear to work in the same way) and it wasn't working. I have made some "progress" though. 

Even though it obviously shouldn't make a difference, I decided to install `terminator` and see whether that worked. Obviously, it works fine when trying to run terminator :-(. 

What is even more infuriating is that if I log in manually to `wsl`, and launch `DISPLAY=$(cat /etc/resolv.conf | grep name | cut -d' ' -f2):0 gnome-terminal`, close it and *then* run the vbs script it *will* open `gnome-terminal` and keep it open. If I kill `vcxsvr.exe` and then let the script relaunch it then the problem starts again. It isn't a matter of time though - if I don't manually log in and launch `gnome-terminal` then it will never successfully get it to stay open - I can launch the script lots of times and the windows always close. So something happens to the `vcxsrv` when `gnome-terminal` gets launched from within `wsl` that stays done even if a window is closed? I'm lost...

Weirdness!

**Comment by tautomer** [comment]
Yep, the .0 doesn't matter. It basically defines which screen you want to use.

I can exactly reproduce your findings. `gnome-terminal` works fine if you maunally launch from terminal once.

I changed the argument line to 

```
args = "-c " & """DISPLAY=$(cat /etc/resolv.conf | grep name | cut -d' ' -f2):0.0 gnome-terminal > ~/out.txt 2>&1"""
```

~All messages are redirected to `~/out.txt`. And guess what?~

~If I luanch `gnome-terminal` from the script, if shows up for a second and then disappear. The error message in `out.txt` reads~

```
libGL error: No matching fbConfigs or visuals found
libGL error: failed to load driver: swrast
# posix_spawn avoided (fd close requested)
# _g_io_module_get_default: Found default implementation dconf (DConfSettingsBackend) for ‘gsettings-backend’
# watch_fast: "/org/gnome/terminal/legacy/" (establishing: 0, active: 0)
# unwatch_fast: "/org/gnome/terminal/legacy/" (active: 0, establishing: 1)
# watch_established: "/org/gnome/terminal/legacy/" (establishing: 0)
```

~If I maunally luanch it, there aren't errors~

```
# posix_spawn avoided (fd close requested)
# _g_io_module_get_default: Found default implementation dconf (DConfSettingsBackend) for ‘gsettings-backend’
# watch_fast: "/org/gnome/terminal/legacy/" (establishing: 0, active: 0)
# unwatch_fast: "/org/gnome/terminal/legacy/" (active: 0, establishing: 1)
# watch_established: "/org/gnome/terminal/legacy/" (establishing: 0)
```

~And now if I run the script now, `gnome-terminal` luanches and output is also good~

```
# posix_spawn avoided (fd close requested)
# _g_io_module_get_default: Found default implementation dconf (DConfSettingsBackend) for ‘gsettings-backend’
# watch_fast: "/org/gnome/terminal/legacy/" (establishing: 0, active: 0)
# unwatch_fast: "/org/gnome/terminal/legacy/" (active: 0, establishing: 1)
# watch_established: "/org/gnome/terminal/legacy/" (establishing: 0)
```

~So... somehow `gnome-terminal` can't find the [software renderer](https://askubuntu.com/questions/541343/problems-with-libgl-fbconfigs-swrast-through-each-update) if it's launched from the script for the first time.~

~However, luanching it maunally doesn't do anything to libGL libraries... I have no idea why... It seems more likely to be a weird bug in `gnome-terminal`.~

No... no matter how `gnome-terminal` is launched for the second time, the libGL errors are gone, so this isn't the issue.

**Comment by tautomer** [comment]
Ok, [here is the solution](https://askubuntu.com/questions/1126850/vbs-script-doesnt-run-gnome-terminal-unless-i-run-the-program-in-terminal-firs)

Add `; read` after your argument. So it will be like

```
args = "-c " & """DISPLAY=$(cat /etc/resolv.conf | grep name | cut -d' ' -f2):0.0 gnome-terminal; read"""
```

The other solution, i.e., lanuching `dbus` first also works.

**Comment by AntonOfTheWoods** [comment]
Thanks for your support on this. The `; read` keeps a `cmd` open but it is definitely a solution for the moment. Thanks!
